Repository ARK-Builders/ARK-Navigator, pull requests merged in 2023-10, with the labels that each got.

#388 Refactor FileUtils & cover unit test
  .gitignore
  app/src/main/java/dev/arkbuilders/navigator/data/utils/DevicePathsExtractor.kt
  app/src/main/java/dev/arkbuilders/navigator/data/utils/DevicePathsExtractorImpl.kt
  app/src/main/java/dev/arkbuilders/navigator/data/utils/FileUtils.kt
  app/src/main/java/dev/arkbuilders/navigator/data/utils/PathExt.kt
  app/src/main/java/dev/arkbuilders/navigator/di/AppComponent.kt
  app/src/main/java/dev/arkbuilders/navigator/di/modules/AppModule.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/dialog/rootsscan/RootsScanDialogFragment.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/dialog/rootsscan/RootsScanDialogPresenter.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/screen/folders/FoldersViewModel.kt
  app/src/test/java/dev/arkbuilders/navigator/data/utils/DevicePathsExtractorTest.kt
  app/src/test/java/dev/arkbuilders/navigator/data/utils/PathExtKtTest.kt
Labels: enhancement

#392 Export test execution result with config
  app/build.gradle
Labels: enhancement

#398 Improve empty state of Folders screen with animation
  app/build.gradle
  app/src/main/assets/folders_empty_folder_list_hint_gif.json
  app/src/main/res/layout/fragment_folders.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#406 Create pull request template
  .github/pull_request_template.md
Labels: enhancement

#401 [enhancement] Improve the UX of Manage folders screen
  app/src/main/java/dev/arkbuilders/navigator/presentation/screen/folders/FoldersFragment.kt
Labels: enhancement, UX

#410 [enhancement] Fix Lint warnings
  .editorconfig
  app/build.gradle
  app/src/main/java/dev/arkbuilders/navigator/data/PermissionsHelper.kt
  app/src/main/java/dev/arkbuilders/navigator/data/stats/AggregatedStatsStorage.kt
  app/src/main/java/dev/arkbuilders/navigator/data/stats/PlainStatsStorage.kt
  app/src/main/java/dev/arkbuilders/navigator/data/stats/StatsStorageRepo.kt
  app/src/main/java/dev/arkbuilders/navigator/data/stats/category/StatsCategoryStorage.kt
  app/src/main/java/dev/arkbuilders/navigator/data/stats/category/TagLabeledNStorage.kt
  app/src/main/java/dev/arkbuilders/navigator/data/stats/category/TagLabeledTSStorage.kt
  app/src/main/java/dev/arkbuilders/navigator/data/stats/category/TagQueriedNStorage.kt
  app/src/main/java/dev/arkbuilders/navigator/data/stats/category/TagQueriedTSStorage.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/dialog/RootPickerDialogFragment.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/dialog/tagssort/TagsSortViewModel.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/navigation/AppNavigator.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/navigation/Screens.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/screen/folders/FoldersViewModel.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/screen/gallery/GalleryFragment.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/screen/gallery/GalleryPresenter.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/screen/resources/ResourcesPresenter.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/screen/resources/adapter/ResourcesGridPresenter.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/view/DefaultPopup.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/view/DepthPageTransformer.kt
  app/src/main/java/dev/arkbuilders/navigator/presentation/view/StackedToasts.kt
  app/src/main/res/layout/dialog_info.xml
  app/src/main/res/layout/item_image.xml
  app/src/main/res/xml/provider_paths.xml
  app/src/test/java/dev/arkbuilders/navigator/stub/ResourceIndexStub.kt
  build.gradle
Labels: enhancement, should be quick
